---
# Install dependencies for mypy and pylint
PRE_COMMANDS:
  - command: &dev-deps pushd /github/workspace; pip install --no-cache-dir --disable-pip-version-check -r requirements.dev.txt; popd
    venv: mypy
  - command: *dev-deps
    venv: pylint

# Disable linters
DISABLE_LINTERS:
  - PYTHON_RUFF
  - PYTHON_FLAKE8
  - PYTHON_PYRIGHT
DISABLE:
  - SPELL

# Linter configuration
PYTHON_MYPY_CONFIG_FILE: "pyproject.toml"
PYTHON_PYLINT_CONFIG_FILE: "pyproject.toml"
PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: "^tests/.*"
COPYPASTE_JSCPD_ARGUMENTS: "--ignore \"**/requirements.*,**/tests/lib/**\""

# Disable errors
COPYPASTE_JSCPD_DISABLE_ERRORS: true
REPOSITORY_CHECKOV_DISABLE_ERRORS: true

# Reporters
MARKDOWN_SUMMARY_REPORTER: true
GITHUB_STATUS_REPORTER: true
SARIF_REPORTER: true
