name: Poetry Version
description: Get/Set Poetry Version
inputs:
  version:
    description: The version to set
    required: false
outputs:
  version:
    description: The version in pyproject.toml
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
  - run: echo cache-key=${{ hashFiles('pyproject.toml') }} >> "$GITHUB_ENV"
    shell: bash
  - id: cache
    uses: actions/cache/restore@v4
    if: inputs.version == null
    with:
      key: ${{ env.cache-key }}
      path: ${{ env.cache-key }}_OUTPUT
  - id: version
    run: |
      if [[ '${{ steps.cache.outputs.cache-hit }}' != 'true' ]]; then
        pipx install poetry
        echo "version=$(poetry version -s -- '${{ inputs.version }}')" > "${{ env.cache-key }}_OUTPUT"
      fi
      cat ${{ env.cache-key }}_OUTPUT >> "$GITHUB_OUTPUT"
    shell: bash
  - uses: actions/cache/save@v4
    with:
      key: ${{ env.cache-key }}
      path: ${{ env.cache-key }}_OUTPUT
  - run: rm -f ${{ env.cache-key }}_OUTPUT
    shell: bash