---
  name: Semver Version

  on:
    workflow_call:
      inputs:
        head:
          description: The HEAD to get changes from
          type: string
          required: true

      outputs:
        current:
          value: ${{ jobs.semver.outputs.current }}
          description: 'The current semver version'
        next:
          value: ${{ jobs.semver.outputs.next }}
          description: 'The next semver version'


  jobs:
    semver:
      runs-on: ubuntu-latest
      outputs:
        current: ${{ steps.semver.outputs.current }}
        next: ${{ steps.semver.outputs.next }}
      steps:
      - uses: actions/checkout@v4
      - uses: ietf-tools/semver-action@v1
        id: semver
        with:
          token: ${{ github.token }}
          branch: ${{ inputs.head }}
          noVersionBumpBehavior: 'patch'
