# Publish a release
---
  name: Publish Release

  on:
    workflow_call:
      inputs:
        body:
          description: 'The body of the release'
          type: string
          required: true

  jobs:
    publish-release:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: write
      steps:
      - uses: actions/checkout@v4
      - name: poetry-version
        id: poetry-version
        run: |
          pipx install poetry
          echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          tag: '${{ steps.poetry-version.outputs.version }}'
          body: '${{ inputs.body }}'
