---
name: 'Reviewdog Lint'

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head:
        type: string
        required: true
        description: HEAD to lint
      pr-number:
        type: string
        required: true
        description: Pull request number
      reporter:
        type: string
        required: true
        description: Reporter to use
        default: github-check

env:
  CI_PULL_REQUEST: ${{ github.event.inputs.pr-number }}
  CI_REPO_OWNER: ${{ github.repository_owner }}
  CI_REPO_NAME: ${{ github.event.repository.name }}
  CI_BRANCH: ${{ github.event.inputs.head }}
  REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: ${{ inputs.reporter }}

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-markdownlint@v0
        with:
          reporter: ${{ inputs.reporter }}

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-black@v1
        with:
          reporter: ${{ inputs.reporter }}

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install-poetry
        run: pipx install poetry mypy
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - uses: tsuyoshicho/action-mypy@v4
        with:
          execute_command: 'poetry run mypy'
          reporter: ${{ inputs.reporter }}

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: dciborow/action-pylint@0.1.0
        with:
          reporter: ${{ inputs.reporter }}
          glob_pattern: '**/*.py'

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-gitleaks@v1
        with:
          reporter: ${{ inputs.reporter }}

  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-trivy@v1
        with:
          trivy_command: filesystem
          trivy_target: '.'
          reporter: ${{ inputs.reporter }}

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-yamllint@v1

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: ${{ inputs.reporter }}
          reviewdog_flags: -guess