# Publish a release
---
  name: Publish Release

  on:
    workflow_call:
      inputs:
        body:
          description: 'The body of the release'
          type: string
          required: true

  jobs:
    rebase-dev-on-main:
      uses: ./.github/workflows/def_rebase.yml
      with:
        base: main
        head: dev

    publish-release:
      runs-on: ubuntu-latest
      environment: prod
      permissions:
        contents: write
      steps:
      - name: poetry-version
        id: poetry-version
        run: |
          pipx install poetry
          echo "version=$(poetry version -s)" >> "$GITHUB_OUTPUTS"
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          tag: '${{ steps.poetry-version.outputs.version }}'
          body: '${{ inputs.body }}'
