---
  name: "MegaLinter"

  on:
    workflow_call:
      inputs:
        event_name:
          type: string
          required: true
          description: Original event name

  concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

  jobs:
    megalinter:
      name: MegaLinter
      runs-on: ubuntu-latest
      permissions:
        contents: write
        issues: write
        pull-requests: write
        statuses: write
      steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oxsecurity/megalinter/flavors/python@v7.8.0
        id: mega-linter
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MEGALINTER_CONFIG: .github/megalinter.yml
          APPLY_FIXES_EVENT: 'none'
          VALIDATE_ALL_CODEBASE: >-
            ${{
              inputs.event_name == 'push' &&
              contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)
            }}
      - name: publish-summary
        if: always() && hashFiles('megalinter-reports/megalinter-report.md') != ''
        run: cat "megalinter-reports/megalinter-report.md" >> "${GITHUB_STEP_SUMMARY}"
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'megalinter-reports/megalinter-report.sarif'

