# Publish a release
---
  name: Publish Release

  on:
    workflow_call:
      inputs:
        body:
          description: 'The body of the release'
          type: string
          required: true

  jobs:
    poetry-version:
      uses: ./.github/workflows/def_poetry-version.yml

    publish-release:
      runs-on: ubuntu-latest
      needs: poetry-version
      permissions:
        pull-requests: write
        contents: write
      steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          tag: ${{ needs.poetry-version.outputs.version }}
          body: ${{ inputs.body }}
