---
  on:
    workflow_call:
      inputs:
        head:
          required: true
          type: string

  name: Run pytest

  jobs:
    pytest:
      runs-on: ubuntu-latest
      permissions:
        checks: write
      steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head }}
      - name: install-poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: poetry-install
        run: poetry install
      - name: pytest
        env:
          TERM: dumb
        run: poetry run pytest --junit-xml=pytest.xml
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: pytest.xml
