on:
  workflow_call:
    inputs:
      repo:
        description: 'The repository to fetch tags from'
        type: string
        required: true
    outputs:
      tags:
        description: 'The tags of the repository'
        value: ${{ jobs.get-tags.outputs.tags }}

jobs:
  get-tags:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: get-tags
        id: get-tags
        run: |
          echo tags=$(
            gh release list \
              --repo '${{ inputs.repo }}' \
              --json tagName \
              --exclude-drafts \
              --exclude-pre-releases \
              --jq '[.[].tagName]'
            ) >> "$GITHUB_OUTPUT"