---
name: 'Reviewdog'

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write
  security-events: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head:
        type: string
        required: true
        description: HEAD to lint
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-markdownlint@v0
        with:
          reporter: github-check

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-black@v1
        with:
          reporter: github-check

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install-poetry
        run: pipx install poetry mypy
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - uses: tsuyoshicho/action-mypy@v4
        with:
          execute_command: 'poetry run mypy'
          reporter: github-check

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: dciborow/action-pylint@0.1.0
        with:
          reporter: github-check
          glob_pattern: '**/*.py'

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-gitleaks@v1
        with:
          reporter: github-check

  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-trivy@v1
        with:
          trivy_command: filesystem
          trivy_target: '.'
          reporter: github-check

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - uses: reviewdog/action-yamllint@v1
