# Use poetry to get/set the version of a project
---
  name: 'Poetry Version'

  on:
    workflow_call:
      inputs:
        version:
          description: New version to set
          type: string
          default: ''

  jobs:
    poetry-version:
      runs-on: ubuntu-latest
      permissions: read-all
      outputs:
        version: ${{ steps.poetry-version.outputs.version }}
      steps:
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - uses: abatilo/actions-poetry@v2
        - name: poetry-version
          id: poetry-version
          run: echo version=$(poetry version -s -- '${{ inputs.version }}') >> '$GITHUB_OUTPUT'
