# Publish a release
---
  name: Generate changelog

  on:
    workflow_call:
      inputs:
        from:
          description: 'The tag to start from'
          type: string
        to:
          description: 'The tag to end at'
          type: string
      outputs:
        changes:
          description: 'The generated changelog'
          value: ${{ jobs.generate-changelog.outputs.changes }}

  jobs:
    generate-changelog:
      runs-on: ubuntu-latest
      outputs:
        changes: ${{ steps.changelog.outputs.changes }}
      steps:
      - uses: actions/checkout@v4
      - uses: requarks/changelog-action@v1
        id: changelog
        with:
          token: ${{ github.token }}
          writeToFile: false
          fromTag: ${{ inputs.from }}
          toTag: ${{ inputs.to }}