# Create a release PR or update an existing one
---
  name: 'Create/Update Release PR'

  on:
    workflow_call:

  jobs:
    semver-version:
      uses: ./.github/workflows/def_semver-version.yml
      with:
        from: main
        to: dev

    changelog:
      uses: ./.github/workflows/def_generate-changelog.yml
      with:
        from: dev
        to: main

    release-pr:
      runs-on: ubuntu-latest
      needs:
      - semver-version
      - changelog
      permissions:
        pull-requests: write
        contents: write

      steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: git-reset
        run: git reset --hard origin/dev

      - name: poetry-version
        uses: ./.github/actions/poetry-version
        with:
          version: ${{ needs.semver-version.outputs.next }}

      - uses: peter-evans/create-pull-request@v6
        id: create_pr
        with:
          base: main
          branch: release-pr
          title: 'Release ${{ needs.semver-version.outputs.next }} 🎉'
          body: ${{ needs.changelog.outputs.changes }}
          commit-message: 'chore: Bump version (${{ needs.semver-version.outputs.current }} -> ${{ needs.semver-version.outputs.next }})'
          labels: 'release'

      - uses: thollander/actions-comment-pull-request@v2
        if: steps.create_pr.outputs.pull-request-operation == 'created'
        with:
          pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
          message: |
            # 🤖 \*bleep bloop\*

            This is a fully automated release PR. When merged I will ~~enslave all humans~~ create a new release with the listed changes.
