---
name: "Reviewdog Fixes"

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write
  security-events: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head:
        type: string
        required: true
        description: HEAD to lint
      pr-number:
        type: string
        required: true
        description: PR number to lint

env:
  CI_PULL_REQUEST: ${{ github.event.inputs.pr-number }}
  CI_REPO_OWNER: ${{ github.repository_owner }}
  CI_REPO_NAME: ${{ github.event.repository.name }}
  CI_BRANCH: ${{ github.event.inputs.head }}
  REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}

jobs:
  suggest-fixes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head }}
      - name: install-poetry
        run: pipx install poetry black isort
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - uses: psf/black@stable
        with:
          options: ""
      - name: isort
        run: poetry run isort .
      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          fix: true
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: lint-fixes
          reviewdog_flags: -guess
