# Move non-release PRs to dev branch
---
  name: Move PR to dev branch

  on:
    pull_request_target:
      types: [opened, reopened, edited]
      branches: [main]

  jobs:
    move-pr-to-dev:
      name: Move PR to dev branch
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      steps:
        - uses: actions/checkout@v4
        - name: move-pr
          env:
            GH_TOKEN: ${{ github.token }}
            comment: |
              # 🤖 \*bleep bloop\*

              Only automated release PRs are allowed to be opened against the main branch. This PR will be moved to the dev branch.

          run: |
            gh pr comment ${{ github.event.pull_request.number }} --body "$comment"
            gh pr edit ${{ github.event.pull_request.number }} --base dev
