# Move non-release PRs to dev branch
---
name: PR Opened/Edit/Reopened on Main

permissions: read-all

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, reopened, edited]
    branches: [main]

concurrency:
  group: ${{ github.event.pull_request.number }}-${{ github.workflow }}

jobs:
  move-pr-to-dev:
    uses: ./.github/workflows/def_move-pr.yml
    permissions:
      pull-requests: write
    with:
      pr-number: ${{ github.event.pull_request.number }}
      base: dev

    pytest:
      name: Run tests
      uses: ./.github/workflows/def_pytest.yml
      permissions:
        checks: write
        pull-requests: write
      concurrency:
        group: ${{ github.ref }}-${{ github.workflow }}-reviewdog-test
      with:
        head: ${{ github.event.pull_request.head.sha }}

    reviewdog-lint:
      name: Lint code
      uses: ./.github/workflows/def_reviewdog-lint.yml
      permissions:
        contents: write
        issues: write
        pull-requests: write
        statuses: write
      concurrency:
        group: ${{ github.ref }}-${{ github.workflow }}-reviewdog-lint
      with:
        head: ${{ github.event.pull_request.head.sha }}
        pr-number: ${{ github.event.pull_request.number }}
        reporter: github-pr-review
