# Move non-release PRs to dev branch
---
name: PR Opened/Edit/Reopened on Main

permissions: read-all

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, reopened, edited]
    branches: [main]

concurrency:
  group: ${{ github.event.pull_request.number }}-${{ github.workflow }}

jobs:
  move-pr-to-dev:
    uses: ./.github/workflows/def_move-pr.yml
    permissions:
      pull-requests: write
    with:
      pr_number: ${{ github.event.pull_request.number }}
      base: dev
