# Create or update a release PR for merging dev -> main
---
  name: Publish Release

  on:
    pull_request_target:
      types: [closed]
      branches: [main]

  jobs:
    semver:
      uses: ./.github/workflows/def_semver.yml
      with:
        branch: ${{ github.event.pull_request.base.ref }}

    publish-release:
      name: Publish Release
      runs-on: ubuntu-latest
      needs: semver
      permissions:
        contents: write
      steps:
        - name: publish-release
          env:
            GH_TOKEN: ${{ github.token }}
          run: |
            gh release create '${{ needs.semver.outputs.next }}' \
              --notes '${{ github.event.pull_request.body }}' \
              --title '${{ needs.semver.outputs.next }}'
