# Create or update a release PR for merging dev -> main
---
  name: Publish Release

  on:
    pull_request_target:
      types: [closed]

  jobs:
    version:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      if: github.event.pull_request.merged == true
      steps:
      - uses: actions/checkout@v4
      - uses: ietf-tools/semver-action@v1
        id: version
        with:
          token: ${{ github.token }}
          branch: ${{ github.event.pull_request.base.ref }}
          noVersionBumpBehavior: 'patch'
      - name: publish-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create '${{ steps.version.outputs.next }}' \
            --notes '${{ github.event.pull_request.body }}' \
            --title '${{ steps.version.outputs.next }}'
