# Run jobs on pull request events
---
  name: Pull Request Workflow
  permissions: read-all

  on:
    pull_request_target:
      branches: '*'
      types: [opened, closed, reopened]

  jobs:
    move-non-release-pr:
      if: |
        github.ref_name == 'main' &&
        github.event.action == 'opened' ||
        github.event.action == 'reopened'
      name: Move non-release PR
      uses: ./.github/workflows/def_move-non-release-pr.yml
      with:
        pull_request_number: ${{ github.event.pull_request.number }}
      permissions:
        pull-requests: write

    publish-release:
      if: |
        github.ref_name == 'main' &&
        github.event.action == 'closed' &&
        github.event.pull_request.merged == true
      name: Publish release
      uses: ./.github/workflows/def_publish-release.yml
      permissions:
        pull-requests: write
        contents: write
      with:
        body: ${{ github.event.pull_request.body }}
