# Run jobs on pull request events
---
  name: Pull Request Workflow
  permissions: read-all

  on:
    pull_request:
      branches:
      - dev
      - main

  jobs:
    publish-release:
      if: |
        github.ref_name == 'main' &&
        github.head_ref == 'release-pr' &&
        github.event.action == 'closed' &&
        github.event.pull_request.merged == true
      name: Publish release
      uses: ./.github/workflows/def_publish-release.yml
      permissions:
        pull-requests: write
        contents: write
      with:
        body: ${{ github.event.pull_request.body }}
