# Create or update a release PR for merging dev -> main
---
  on:
    push:
      branches:
        - dev

  jobs:
    changes:
      runs-on: ubuntu-latest
      outputs:
        changelog: ${{ steps.changelog.outputs.changelog }}
      steps:
      - uses: mikepenz/release-changelog-builder-action@v3
        id: changelog
        with:
          fromTag: main
          toTag: dev
          commitMode: true

    version:
      runs-on: ubuntu-latest
      outputs:
        current: ${{ steps.semver.outputs.current }}
        next: ${{ steps.semver.outputs.next }}
      steps:
      - uses: actions/checkout@v4
      - uses: ietf-tools/semver-action@v1
        id: semver
        with:
          token: ${{ github.token }}
          branch: main

    release-pr:
      runs-on: ubuntu-latest
      needs: [changes, version]
      permissions:
        pull-requests: write
      steps:
        - uses: actions/checkout@v4
        - name: Create or update release PR
          env:
            GH_TOKEN: ${{ github.token }}
            title: Release ${{ needs.version.outputs.next }} 🚀
            body: |
              # 🤖 \*bleep bloop\*

              This is a fully automated release PR. When merged I will ~~enslave all humans~~ create a new release with the listed changes.

              ${{ needs.changes.outputs.changelog }}
          run: |
            {
              gh pr create --base main --head dev --title '${{ env.title }}' --body '${{ needs.changes.outputs.changelog }}' --label 'release'
            } || {
              gh pr edit dev --base main --title '${{ env.title }}' --body '${{ env.body }}' --add-label 'release'
            }